# Generated by Django 5.0.14 on 2026-09-23 01:12

import django.db.models.deletion
from django.db import migrations, models


def copiar_proyectos_desde_secciones(apps, schema_editor):
    Archivo = apps.get_model('proyectos', 'Archivo')
    for archivo in Archivo.objects.select_related('seccion').all():
        archivo.proyecto_id = archivo.seccion.proyecto_id
        archivo.save(update_fields=['proyecto'])


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='proyectos.proyecto'),
        ),
        migrations.RunPython(copiar_proyectos_desde_secciones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='archivo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='proyectos.proyecto'),
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='seccion',
        ),
        migrations.AddField(
            model_name='archivo',
            name='global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='equipo_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
